### ISSUE TITLE
Running default parameters OOB returns Floating-point exception 

### ISSUE THREAD

**Issue by lucas-spangher** [lesgo-jhu/lesgo#12]
Hey, I'm new to running this simulation, so I'm not sure what normal behavior is like or how to diagnose this error, but compiling and then running OOB lesgo.config returns this: 

`(base) [lucas_spangher@ln002 lesgo]$ ./lesgo-mpi-cps-turbines-scalars`

`Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.`

`Backtrace for this error:`
`#0  0x2b2966ecf3ff in ???`
`#1  0x544965 in ???`
`#2  0x4327fb in ???`
`#3  0x487979 in ???`
`#4  0x40335c in ???`
`#5  0x2b2966ebb554 in ???`
`#6  0x4033ab in ???`
`#7  0xffffffffffffffff in ???`
`Floating point exception`

Any pointers or advice appreciated, no pun intended!

**Comment by ghanesh91** [comment]
Hi Lucas, could you please share the details of the simulation you are trying to set up?
The executable lesgo-mpi-cps-turbines-scalars should be used in the Concurrent/wind-turbine domain of a Concurrent-Precursor Simulation (CPS).

**Comment by wl-cpu** [comment]
> Hey, I'm new to running this simulation, so I'm not sure what normal behavior is like or how to diagnose this error, but compiling and then running OOB lesgo.config returns this:
> 
> `(base) [lucas_spangher@ln002 lesgo]$ ./lesgo-mpi-cps-turbines-scalars`
> 
> `Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.`
> 
> `Backtrace for this error:` `#0 0x2b2966ecf3ff in ???` `#1 0x544965 in ???` `#2 0x4327fb in ???` `#3 0x487979 in ???` `#4 0x40335c in ???` `#5 0x2b2966ebb554 in ???` `#6 0x4033ab in ???` `#7 0xffffffffffffffff in ???` `Floating point exception`
> 
> Any pointers or advice appreciated, no pun intended!


通用

The executable program is run through mpirun (openmpi or MPICH). Please check the input of the command
